# Site settings
title: ValyrianSteel Blog
description: ValyrianSteel-Blog A Elegant by Jekyll
keywords: Modern, Blogging, Fun
author: Valyrian & Wferr
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ValyrianSteel.github.io" # the base hostname & protocol for your site
